Fix: jss-debrepo-update repo resigning
Signed-off-by: Miroslav Safr <Miroslav.Safr@tieto.com>

diff --git a/jss-debrepo-update b/jss-debrepo-update
--- a/jss-debrepo-update
+++ b/jss-debrepo-update
@@ -36,10 +36,10 @@ while [ $# -gt 0 ]; do
         -h|--help)  usage ; exit ;;
         -gn|--gpg-name) shift ; GPG_NAME=$1 ;
             GPGKEY=`gpg --list-keys | grep "$GPG_NAME" -1 | grep pub -m 1 | sed "s/.*\///" | awk -F " " '{print $1}'`
-        if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
+        	if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
         -gk|--gpg-key) shift ; GPGKEY=$1 ;
             GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid -m 1| sed "s/uid *//"`
-        if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
+        	if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
         -ns|--no-sign) NO_SIGN=yes ;;
         *) REPO_DIR=$1 ;;
     esac
@@ -118,9 +118,16 @@ cd $REPO_DIR
     
     #sign release
     if [ -z "$NO_SIGN" ]; then
-        gpg --clearsign -o ./InRelease ./Release
-        gpg -abs -o ./Release.gpg ./Release
-    fi
+		echo "signing repo by $GPG_NAME - $GPGKEY"
+        gpg --clearsign --local-user $GPGKEY -o ./InRelease ./Release 
+        if [ $? -ne 0 ]; then
+            echo "repo resign failed."
+        fi
+        gpg -abs --local-user $GPGKEY -o ./Release.gpg ./Release
+        if [ $? -ne 0 ]; then
+            echo "generating gpg sign failed."
+        fi
+   fi
     
     rm -f $REPO_DIR/.lock
     cd $PWD
