Int: code formatting
Signed-off-by: Miroslav Safr <Miroslav.Safr@tieto.com>

diff --git a/jss-backup b/jss-backup
--- a/jss-backup
+++ b/jss-backup
@@ -30,23 +30,23 @@ usage() {
 FILE_EXT=tar.bz2
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -V|--version)       echo "`basename $0` ${VERSION} ${VERSION_DATE}"; exit 0 ;;
-    -h|--help)          usage ; exit ;;
-    -bd|--backup-dir)   shift ; BACKUP_DIR="$1" ;;
-    -fp|--file-prefix)  shift ; FILE_PREFIX="$1" ;;
-    -fs|--file-suffix)  shift ; FILE_SUFFIX="$1" ;;
-    -c|--compression)   shift ; FILE_EXT="$1"
-                	    case "$FILE_EXT" in
-                            tar.bz2|zip|tar.gz) ;;
-                			*) fail "Wrong compression type: $FILE_EXT" ;;
-                		esac ;;
-    -e|--exclude)       shift ;  EXCLUDE_LIST="$1" ;;
-    -ff|--full-filenames) USE_FULL_PATHS=1 ;;
-    -v|--verbose)       VERBOSE_FLAG=1 ;;
-     *)                 DATA_DIR="$1" ;;
-  esac
-  shift
+    case "$1" in
+        -V|--version)       echo "`basename $0` ${VERSION} ${VERSION_DATE}"; exit 0 ;;
+        -h|--help)          usage ; exit ;;
+        -bd|--backup-dir)   shift ; BACKUP_DIR="$1" ;;
+        -fp|--file-prefix)  shift ; FILE_PREFIX="$1" ;;
+        -fs|--file-suffix)  shift ; FILE_SUFFIX="$1" ;;
+        -c|--compression)   shift ; FILE_EXT="$1"
+            case "$FILE_EXT" in
+                tar.bz2|zip|tar.gz) ;;
+                *) fail "Wrong compression type: $FILE_EXT" ;;
+        esac ;;
+        -e|--exclude)       shift ;  EXCLUDE_LIST="$1" ;;
+        -ff|--full-filenames) USE_FULL_PATHS=1 ;;
+        -v|--verbose)       VERBOSE_FLAG=1 ;;
+        *)                 DATA_DIR="$1" ;;
+    esac
+    shift
 done
 
 [ -n "$DATA_DIR" ] || DATA_DIR=`pwd`
@@ -73,11 +73,11 @@ verbose "USE_FULL_PATHS:$USE_FULL_PATHS pwd=`pwd` DATA_DIR=$DATA_DIR"
 
 case "$FILE_EXT" in
     tar.bz2)  [ -n "$EXCLUDE_LIST" ] && EXCLUDE_FLAG="--exclude=$EXCLUDE"
-              tar "$EXCLUDE_FLAG" -cvjf "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
+    tar "$EXCLUDE_FLAG" -cvjf "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
     zip)      [ -n "$EXCLUDE_LIST" ] && EXCLUDE_FLAG="--exclude $EXCLUDE"
-              zip -r "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
+    zip -r "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
     tar.gz)   [ -n "$EXCLUDE_LIST" ] && EXCLUDE_FLAG="--exclude=$EXCLUDE"
-              tar "$EXCLUDE_FLAG" -cvzf "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
+    tar "$EXCLUDE_FLAG" -cvzf "$FULL_BACKUP_FILE" "$DATA_DIR" || fail "compression failed" ;;
     *) fail "Wrong compression type: $FILE_EXT" ;;
 esac
 
diff --git a/jss-debrepo-signcheck b/jss-debrepo-signcheck
--- a/jss-debrepo-signcheck
+++ b/jss-debrepo-signcheck
@@ -8,70 +8,67 @@ VERSION=NA
 VERSION_DATE=NA
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -v|--verbose)
-               VERBOSE=--verbose
-               ;;
-	* )    REPO_DIR=$1;
-	       ;;
-  esac
-  shift
+    case "$1" in
+        -v|--verbose) VERBOSE=--verbose  ;;
+        * )    REPO_DIR=$1 ;;
+    esac
+    shift
 done
 
 #check parameter
 if [ -z "$REPO_DIR" ];	then
-	REPO_DIR=`pwd`
+    REPO_DIR=`pwd`
 fi
 
 if [ ! -d "$REPO_DIR" ];	then
-	echo "not existing dir $1, exiting.."
-	exit 1
+    echo "not existing dir $1, exiting.."
+    exit 1
 fi
 
 #first key if not defined
 if [ -z "$GPGKEY" ]; then
-	GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
-	echo "getting first GPGKEY: $GPGKEY"
+    GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
+    echo "getting first GPGKEY: $GPGKEY"
 fi
 if [ -z "$GPGKEY" ]; then
-	echo "GPGKEY not found, exiting..."
-	exit 1
+    echo "GPGKEY not found, exiting..."
+    exit 1
 fi
 
 COUNT_OK=0
 COUNT_NOK=0
 PACKAGES=$(find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes|dsc)$')
 if [ ! -z "$PACKAGES" ]; then
-FIFOOK=/tmp/SIGNCHECK_COUNT_OK.$$
-FIFONOK=/tmp/SIGNCHECK_COUNT_NOK.$$
-trap 'rm -f $FIFOOK' 0
-trap 'rm -f $FIFONOK' 0
-mkfifo $FIFOOK 2> /dev/null
-mkfifo $FIFONOK 2> /dev/null
-echo "${PACKAGES}" | \
-{ while IFS='\n' read -r PACKAGE ; do
-	#echo "$PACKAGE";
-	RES=`dpkg-sig -c $PACKAGE | grep $GPGKEY | grep GOODSIG `
-	#echo "$RES"
-	if [ $? -ne 0 ]; then
-		echo "$PACKAGE not signed by $GPGKEY: $RES"
-		COUNT_NOK=$(($COUNT_NOK + 1)) 
-	else
-		COUNT_OK=$(($COUNT_OK + 1)) 
-	fi
-  done
-  echo "$COUNT_OK" > $FIFOOK &
-  echo "$COUNT_NOK" > $FIFONOK &
-}
-#pass the value back to script
-if [ -e $FIFO ]; then
-	read COUNT_OK < $FIFOOK
-	read COUNT_NOK < $FIFONOK
-	wait $!
-fi
+    FIFOOK=/tmp/SIGNCHECK_COUNT_OK.$$
+    FIFONOK=/tmp/SIGNCHECK_COUNT_NOK.$$
+    trap 'rm -f $FIFOOK' 0
+    trap 'rm -f $FIFONOK' 0
+    mkfifo $FIFOOK 2> /dev/null
+    mkfifo $FIFONOK 2> /dev/null
+    echo "${PACKAGES}" | \
+    { while IFS='\n' read -r PACKAGE ; do
+            #echo "$PACKAGE";
+            RES=`dpkg-sig -c $PACKAGE | grep $GPGKEY | grep GOODSIG `
+            #echo "$RES"
+            if [ $? -ne 0 ]; then
+                echo "$PACKAGE not signed by $GPGKEY: $RES"
+                COUNT_NOK=$(($COUNT_NOK + 1))
+            else
+                COUNT_OK=$(($COUNT_OK + 1))
+            fi
+        done
+        echo "$COUNT_OK" > $FIFOOK &
+        echo "$COUNT_NOK" > $FIFONOK &
+    }
+    #pass the value back to script
+    if [ -e $FIFO ]; then
+        read COUNT_OK < $FIFOOK
+        read COUNT_NOK < $FIFONOK
+        wait $!
+    fi
 fi
 echo "packages signed OK:$COUNT_OK/NOK:$COUNT_NOK"
 
 if [ $COUNT_NOK -ne 0 ]; then
-	exit 2
+    exit 2
 fi
diff --git a/jss-debrepo-update b/jss-debrepo-update
--- a/jss-debrepo-update
+++ b/jss-debrepo-update
@@ -1,9 +1,9 @@
 #!/bin/sh
 #jenkins support scripts - http://safrm.net/projects/jenkins-support-scripts
 #author: Miroslav Safr <miroslav.safr@gmail.com>
-#updates deb repos 
+#updates deb repos
 #
-#key for signing: 1.by argument, 2. exported GPGKEY 3. first key 
+#key for signing: 1.by argument, 2. exported GPGKEY 3. first key
 VERSION=NA
 VERSION_DATE=NA
 usage() {
@@ -15,8 +15,8 @@ usage() {
     echo " -k,  --keep <N> ...................... keep N versions of one packages"
     echo " -sn, --sign-name <name> .............. name for deb-sign (max 9 char)"
     echo " -gn, --gpg-name <gpg-name> ........... use gpg name for signing by name"
-    echo " -gk, --gpg-key <gpg-key> ............. use gpg key for signing by key"                
-    echo " -ns, --no-sign ....................... don't check signs and don't sign repo"                
+    echo " -gk, --gpg-key <gpg-key> ............. use gpg key for signing by key"
+    echo " -ns, --no-sign ....................... don't check signs and don't sign repo"
     echo " -m, --multiarch ...................... create mixed arch repo"
     echo " -v,  --verbose ....................... prints more output"
     echo " -h,  --help .......................... shows command line help"
@@ -27,32 +27,32 @@ usage() {
 KEEP_PKGS=2
 EXIT_CODE=0
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -k|--keep) shift ; KEEP_PKGS="$1" ;;
-    -v|--verbose) VERBOSE=--verbose ;;
-	-sn|--sign-name) shift ; SIGN_NAME="$1" ;;
-	-m|--multiarch)  MULTIARCH=-m ;;
-    -h|--help)  usage ; exit ;;
-    -gn|--gpg-name) shift ; GPG_NAME=$1 ;
-		GPGKEY=`gpg --list-keys | grep "$GPG_NAME" -1 | grep pub -m 1 | sed "s/.*\///" | awk -F " " '{print $1}'`
-		if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
-    -gk|--gpg-key) shift ; GPGKEY=$1 ; 
-		GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid -m 1| sed "s/uid *//"`
-		if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
-    -ns|--no-sign) NO_SIGN=yes ;;
-	*) REPO_DIR=$1 ;;
-  esac
-  shift
+    case "$1" in
+        -k|--keep) shift ; KEEP_PKGS="$1" ;;
+        -v|--verbose) VERBOSE=--verbose ;;
+        -sn|--sign-name) shift ; SIGN_NAME="$1" ;;
+        -m|--multiarch)  MULTIARCH=-m ;;
+        -h|--help)  usage ; exit ;;
+        -gn|--gpg-name) shift ; GPG_NAME=$1 ;
+            GPGKEY=`gpg --list-keys | grep "$GPG_NAME" -1 | grep pub -m 1 | sed "s/.*\///" | awk -F " " '{print $1}'`
+        if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
+        -gk|--gpg-key) shift ; GPGKEY=$1 ;
+            GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid -m 1| sed "s/uid *//"`
+        if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
+        -ns|--no-sign) NO_SIGN=yes ;;
+        *) REPO_DIR=$1 ;;
+    esac
+    shift
 done
 
 #check parameter
 if [ -z "$REPO_DIR" ];	then
-	REPO_DIR=`pwd`
+    REPO_DIR=`pwd`
 fi
 
 if [ -z "$REPO_DIR" ] || [ ! -w "$REPO_DIR" ]; then
-	echo "not existing dir $REPO_DIR or $USER does not have writable permissions, exiting.."
-	exit 1
+    echo "not existing dir $REPO_DIR or $USER does not have writable permissions, exiting.."
+    exit 1
 fi
 
 PWD=`pwd`
@@ -63,64 +63,64 @@ cd $REPO_DIR
     exec 8> $REPO_DIR/.lock ;
     flock --timeout 120 -e 8
     echo " $$ locking repo $REPO_DIR at `date +'%T'`"
-
+    
     #clean up repo
-    rm -f $REPO_DIR/Packages $REPO_DIR/Packages.gz $REPO_DIR/Sources $REPO_DIR/Sources.gz $REPO_DIR/Release $REPO_DIR/InRelease $REPO_DIR/Release.gpg 
-
+    rm -f $REPO_DIR/Packages $REPO_DIR/Packages.gz $REPO_DIR/Sources $REPO_DIR/Sources.gz $REPO_DIR/Release $REPO_DIR/InRelease $REPO_DIR/Release.gpg
+    
     #clean up packages
     OLDDEBS=`jss-debrepo-repomanage --keep $KEEP_PKGS --old $REPO_DIR 2>/dev/null`
     echo "Cleaning:	$OLDDEBS"
     if [ -n "$OLDDEBS" ]; then
         echo "$OLDDEBS" | xargs rm -rf
     fi
-
+    
     if [ -z "$NO_SIGN" ]; then
         #first key if not defined
         if [ -z "$GPGKEY" ]; then
-	        echo "getting first GPGKEY.."
-	        GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
+            echo "getting first GPGKEY.."
+            GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
         fi
         if [ -z "$GPGKEY" ]; then
-	        echo "GPGKEY not found, exiting..."
-	        exit 1
+            echo "GPGKEY not found, exiting..."
+            exit 1
         fi
         GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
-        if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi 
-
+        if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi
+        
         #check signs and resign
         jss-debrepo-signcheck $REPO_DIR
         if [ $? -ne 0 ]; then
-          echo "not sign packages in repo - resigning"
-          PACKAGES=`find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes)$'`
-          echo "${PACKAGES}" | \
-          { while IFS='\n' read -r ENTRY ;
-          do
-	          echo "test:$ENTRY"
-	          RES=`dpkg-sig -c $ENTRY | grep $GPGKEY`
-	          if [ $? -ne 0 ]; then
-		          echo "signing> "$SIGN_NAME" KEY:$GPGKEY FILE:$ENTRY"
-		          dpkg-sig -s "$SIGN_NAME" -k $GPGKEY $ENTRY
-            	fi
-          done
-          }
-        else 
-          echo "jss-debrepo-signcheck=0"
+            echo "not sign packages in repo - resigning"
+            PACKAGES=`find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes)$'`
+            echo "${PACKAGES}" | \
+            { while IFS='\n' read -r ENTRY ;
+                do
+                    echo "test:$ENTRY"
+                    RES=`dpkg-sig -c $ENTRY | grep $GPGKEY`
+                    if [ $? -ne 0 ]; then
+                        echo "signing> "$SIGN_NAME" KEY:$GPGKEY FILE:$ENTRY"
+                        dpkg-sig -s "$SIGN_NAME" -k $GPGKEY $ENTRY
+                    fi
+                done
+            }
+        else
+            echo "jss-debrepo-signcheck=0"
         fi
     fi
-
+    
     #recreate repo
     dpkg-scanpackages $MULTIARCH . 2> /dev/null  >   ./Packages
-    cat ./Packages | gzip -9 >  ./Packages.gz 
+    cat ./Packages | gzip -9 >  ./Packages.gz
     dpkg-scansources  . 2> /dev/null  >  ./Sources
-    cat ./Sources | gzip -9 >  ./Sources.gz 
+    cat ./Sources | gzip -9 >  ./Sources.gz
     apt-ftparchive release . > ./Release
-
+    
     #sign release
     if [ -z "$NO_SIGN" ]; then
         gpg --clearsign -o ./InRelease ./Release
         gpg -abs -o ./Release.gpg ./Release
     fi
-
+    
     rm -f $REPO_DIR/.lock
     cd $PWD
 ) || exit 1
diff --git a/jss-docs-update b/jss-docs-update
--- a/jss-docs-update
+++ b/jss-docs-update
@@ -22,32 +22,32 @@ usage() {
 }
 
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -h | --help) 
-        usage 
-        exit 
+    case "$1" in
+        -h | --help)
+            usage
+            exit
         ;;
-    -sv|--set-version) shift
-               APPVER_VERSION="$1"
-               OPTIND_SAVE=$OPTIND
-               ;;
-    -V | --version) echo "$BASENAME ${VERSION} ${VERSION_DATE}"
-              exit 0
-              ;;  
-    * )
-        if [ -z "$DOC_DIR" ] ; then
-            DOC_DIR="$1" ;
-        else
-            echo "Directory has to exist and there can be only one directory argument, exiting.."
-            exit 1
-        fi 
+        -sv|--set-version) shift
+            APPVER_VERSION="$1"
+            OPTIND_SAVE=$OPTIND
         ;;
-  esac
-  shift
+        -V | --version) echo "$BASENAME ${VERSION} ${VERSION_DATE}"
+            exit 0
+        ;;
+        * )
+            if [ -z "$DOC_DIR" ] ; then
+                DOC_DIR="$1" ;
+            else
+                echo "Directory has to exist and there can be only one directory argument, exiting.."
+                exit 1
+            fi
+        ;;
+    esac
+    shift
 done
 
 if [ -z "$DOC_DIR" ] || [ ! -e "$DOC_DIR" ]; then
-	DOC_DIR="./"
+    DOC_DIR="./"
 fi
 
 command_exists () {
@@ -55,18 +55,18 @@ command_exists () {
 }
 
 if ! command_exists xsltproc ; then
-	echo "xsltproc does not exist, exiting.."
-	exit 1
+    echo "xsltproc does not exist, exiting.."
+    exit 1
 fi
 
 MANXSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl
 if [ ! -e $MANXSL ]; then
-	MANXSL=http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
+    MANXSL=http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
 fi
 
 HTMLXSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/html/docbook.xsl
 if [ ! -e $HTMLXSL ]; then
-	HTMLXSL=http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl
+    HTMLXSL=http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl
 fi
 
 #trick with setting positional parameters to pass version argument
@@ -83,19 +83,19 @@ if  command_exists jss-xml-validator ; then
         DOCBOOK=/usr/share/sgml/docbook/xml-dtd-4.5/docbookx.dtd
         if [ -e $DOCBOOK ]; then
             DTDFLAG="-dtd $DOCBOOK"
-        else 
+        else
             echo "DTD skipped, cannot find docbookx.dtd, maybe docbook-dtds/docbook-xml package is not installed.. "
             DTDFLAG=
         fi
     fi
-
-    jss-xml-validator  "$DOC_DIR" $DTDFLAG 
-	if [ $? != 0 ]; then
-		echo "Syntax errors"
-		exit 1
-	fi
+    
+    jss-xml-validator  "$DOC_DIR" $DTDFLAG
+    if [ $? != 0 ]; then
+        echo "Syntax errors"
+        exit 1
+    fi
 else
-	echo  "Syntax and validity check skipped (install jenkins-support-scripts..)"
+    echo  "Syntax and validity check skipped (install jenkins-support-scripts..)"
 fi
 
 TEMP_DIR="$DOC_DIR/tmp"
@@ -104,7 +104,7 @@ rm -fr $TEMP_DIR && mkdir $TEMP_DIR
 for PAGEXML in $(  find $DOC_DIR -type f -name "*.xml" )
 do
     cp $PAGEXML $TEMP_DIR
-  	PAGENAME=`basename $PAGEXML`
+    PAGENAME=`basename $PAGEXML`
     sed -i".bkp" "1,/<productnumber>/s/<productnumber>.*/<productnumber>$APP_SHORT_VERSION_TAG<\/productnumber>/" $TEMP_DIR/$PAGENAME  && rm -f $TEMP_DIR/$PAGENAME.bkp
     sed -i".bkp" "1,/<\/date>/s/<date>.*/<date>$APP_BUILD_DATE<\/date>/" $TEMP_DIR/$PAGENAME  && rm -f $TEMP_DIR/$PAGENAME.bkp
 done
@@ -112,13 +112,13 @@ done
 #generate man and html pages
 for PAGEXML in $(  find $TEMP_DIR -type f -name "*.xml" )
 do
-	PAGENAME=`basename $PAGEXML`
-	HTMLNAME="${PAGENAME%%.*}.html"
-	MANPAGENAME="${PAGENAME%.*}"
-	if [ -e $DOC_DIR/htmlpages ]; then
-    		xsltproc -o $DOC_DIR/htmlpages/$HTMLNAME $HTMLXSL $PAGEXML
-	fi
-	if [ -e $DOC_DIR/manpages ]; then
-    		xsltproc -o $DOC_DIR/manpages/$MANPAGENAME $MANXSL $PAGEXML
-	fi
+    PAGENAME=`basename $PAGEXML`
+    HTMLNAME="${PAGENAME%%.*}.html"
+    MANPAGENAME="${PAGENAME%.*}"
+    if [ -e $DOC_DIR/htmlpages ]; then
+        xsltproc -o $DOC_DIR/htmlpages/$HTMLNAME $HTMLXSL $PAGEXML
+    fi
+    if [ -e $DOC_DIR/manpages ]; then
+        xsltproc -o $DOC_DIR/manpages/$MANPAGENAME $MANXSL $PAGEXML
+    fi
 done
diff --git a/jss-html-validator b/jss-html-validator
--- a/jss-html-validator
+++ b/jss-html-validator
@@ -23,28 +23,28 @@ FILE_COUNT=0
 ERROR_COUNT=0
 ERROR_FILES_COUNT=0
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -h | --help) 
-        usage 
-        exit 
+    case "$1" in
+        -h | --help)
+            usage
+            exit
         ;;
-    * )      
-        if [ -z "$SEARCH_DIR" ] && [ -e "$1" ] ; then
-            SEARCH_DIR=$1 ;
-        else
-            echo "Directory has to exist and there can be only one directory argument, exiting.."
-            exit 1
-        fi 
+        * )
+            if [ -z "$SEARCH_DIR" ] && [ -e "$1" ] ; then
+                SEARCH_DIR=$1 ;
+            else
+                echo "Directory has to exist and there can be only one directory argument, exiting.."
+                exit 1
+            fi
         ;;
-  esac
-  shift
+    esac
+    shift
 done
 
 if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
-	SEARCH_DIR="./"
+    SEARCH_DIR="./"
 fi
 
-#check if terminal supports colors 
+#check if terminal supports colors
 COLORS=
 if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
     COLORS=" --color=always ";
@@ -52,8 +52,8 @@ fi
 
 #check dependencies
 if ! type tidy >/dev/null 2>&1; then
-  echo "Not installed tidy, exiting.."
-  exit 1
+    echo "Not installed tidy, exiting.."
+    exit 1
 fi
 
 FIND_WHOLENAME_FLAG="-wholename"
@@ -65,22 +65,22 @@ FILES_COUNT=`echo "$FILES" | grep -v '^$' | wc -l `
 
 echo "${FILES}" | \
 { while IFS='\n' read -r FILE ; do
-	ERRORS=`tidy -q -errors $FILE  2>&1`
-    if [ $? != 0 ]; then
-        EC=`echo "$ERRORS" | grep -v '^$' | wc -l `
-        if [ -z "$COLORS" ]; then
-            echo "$FILE ($EC)";
-        else
-            echo "\033[01;34m$FILE\033[0m \033[01;31m($EC)\033[0m";
+        ERRORS=`tidy -q -errors $FILE  2>&1`
+        if [ $? != 0 ]; then
+            EC=`echo "$ERRORS" | grep -v '^$' | wc -l `
+            if [ -z "$COLORS" ]; then
+                echo "$FILE ($EC)";
+            else
+                echo "\033[01;34m$FILE\033[0m \033[01;31m($EC)\033[0m";
+            fi
+            echo "$ERRORS"
+            ERROR_COUNT=$(($ERROR_COUNT + $EC)) ;
+            ERROR_FILES_COUNT=$(($ERROR_FILES_COUNT + 1)) ;
         fi
-        echo "$ERRORS"
-        ERROR_COUNT=$(($ERROR_COUNT + $EC)) ;
-        ERROR_FILES_COUNT=$(($ERROR_FILES_COUNT + 1)) ;
-    fi
-  done
-  
-  ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
-  echo "$BASENAME found \033[42m$ERROR_COUNT problems in $ERROR_FILES_COUNT files (checked $FILES_COUNT files) \033[0m, took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
-  exit $ERROR_COUNT
+    done
+    
+    ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
+    echo "$BASENAME found \033[42m$ERROR_COUNT problems in $ERROR_FILES_COUNT files (checked $FILES_COUNT files) \033[0m, took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
+    exit $ERROR_COUNT
 } || exit 2
 
diff --git a/jss-jenkins-backup b/jss-jenkins-backup
--- a/jss-jenkins-backup
+++ b/jss-jenkins-backup
@@ -15,16 +15,16 @@ FAST=--exclude=workspace/*
 BACKUP_FILTER=$FAST
 TAR_FILE=$BACKUP_DIR/jenkins_$TIMESTAMP.tar.bz2
 
-if [ ! -d $BACKUP_DIR ]; then  
-	mkdir -p $BACKUP_DIR 
+if [ ! -d $BACKUP_DIR ]; then
+    mkdir -p $BACKUP_DIR
 fi
 
 tar $BACKUP_FILTER -cvjf $TAR_FILE  $JENKINS_ROOT_DIR/* /etc/sysconfig/jenkins
-if [ $? -eq 0 ]; then 
-        SIZE=`du -h $TAR_FILE | awk -F " " '{print $1}'`
-	echo "backup saved to $TAR_FILE"
-	echo "size $SIZE"
+if [ $? -eq 0 ]; then
+    SIZE=`du -h $TAR_FILE | awk -F " " '{print $1}'`
+    echo "backup saved to $TAR_FILE"
+    echo "size $SIZE"
 else
-	echo "backup error!"
-	exit 1
+    echo "backup error!"
+    exit 1
 fi
diff --git a/jss-rpmrepo-update b/jss-rpmrepo-update
--- a/jss-rpmrepo-update
+++ b/jss-rpmrepo-update
@@ -12,11 +12,11 @@ usage() {
     echo "  OPTIONS: "
     echo "  -rp, --resign-packages ............... check and resign packages"
     echo "  -gn, --gpg-name <gpg-name> ........... use gpg name for signing by name"
-    echo "  -gk, --gpg-key <gpg-key> ............. use gpg key for signing by key"                
+    echo "  -gk, --gpg-key <gpg-key> ............. use gpg key for signing by key"
     echo "  -k,  --keep <N> ...................... keep N versions of one packages"
     echo "  -rr, --recreate-repo ................. recreate repodata insted of update"
     echo "  -cl, --changelog-limit <N> ........... limits changelog entries in repo db"
-    echo "  -ns, --no-sign ....................... don't check signs and don't sign repo"                
+    echo "  -ns, --no-sign ....................... don't check signs and don't sign repo"
     echo "  -v,  --verbose ....................... prints more output"
     echo "  -h,  --help .......................... shows command line help"
     echo "  -V,  --version  ...................... prints version of scripts"
@@ -25,43 +25,42 @@ usage() {
 KEEP_PKGS=2
 UPDATE_REPO_FLAG=--update
 while [ $# -gt 0 ]; do
-  case "$1" in
-    -v|--verbose) VERBOSE=--verbose ;;
-    -V|--version) echo "`basename $0` ${VERSION} ${VERSION_DATE}" ;  exit 0 ;;  
-    -h|--help) usage ; exit ;;
-    -cl|--changelog-limit) shift ; CLL_FLAG="--changelog-limit=$1" ;;
-    -rp|--resign-packages) RESIGN_PACKAGES=1 ;;
-    -rr|--recreate-repo) UPDATE_REPO_FLAG=	;;
-    -k|--keep) shift ; KEEP_PKGS=$1 ;;
-    -ns|--no-sign) NO_SIGN=yes ;;
-    -gn|--gpg-name) shift ; GPG_NAME=$1 ;
-		GPGKEY=`gpg --list-keys | grep "$GPG_NAME" -1 | grep pub -m 1 | sed "s/.*\///" | awk -F " " '{print $1}'`
-		if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
-    -gk|--gpg-key) shift ; GPGKEY=$1 ; 
-		GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
-		if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
-
-	*)  if [ -z "$REPO_DIR" ]; then
-            REPO_DIR=$1 ;
-        else
-            echo "Wrong argument '$1' , exiting.."; 
-            usage; 
-            exit 1;        
-        fi 
+    case "$1" in
+        -v|--verbose) VERBOSE=--verbose ;;
+        -V|--version) echo "`basename $0` ${VERSION} ${VERSION_DATE}" ;  exit 0 ;;
+        -h|--help) usage ; exit ;;
+        -cl|--changelog-limit) shift ; CLL_FLAG="--changelog-limit=$1" ;;
+        -rp|--resign-packages) RESIGN_PACKAGES=1 ;;
+        -rr|--recreate-repo) UPDATE_REPO_FLAG=	;;
+        -k|--keep) shift ; KEEP_PKGS=$1 ;;
+        -ns|--no-sign) NO_SIGN=yes ;;
+        -gn|--gpg-name) shift ; GPG_NAME=$1 ;
+            GPGKEY=`gpg --list-keys | grep "$GPG_NAME" -1 | grep pub -m 1 | sed "s/.*\///" | awk -F " " '{print $1}'`
+        if [ -z "$GPGKEY" ]; then echo "wrong gpg name $GPG_NAME" ; exit 1 ; fi ;;
+        -gk|--gpg-key) shift ; GPGKEY=$1 ;
+            GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
+	        if [ -z "$GPG_NAME" ]; then echo "wrong gpg key $GPGKEY" ; exit 1 ; fi ;;
+        *)  if [ -z "$REPO_DIR" ]; then
+                REPO_DIR=$1 ;
+            else
+                echo "Wrong argument '$1' , exiting.."
+                usage
+                exit 1
+            fi
         ;;
-  esac
-  shift
+    esac
+    shift
 done
 
 #check parameter
 if [ -z "$REPO_DIR" ];	then
-	REPO_DIR=`pwd`
+    REPO_DIR=`pwd`
 fi
 
 #check dir
 if [ -z "$REPO_DIR" ] || [ ! -w "$REPO_DIR" ]; then
-	echo "not existing dir $REPO_DIR or $USER does not have writable permissions, exiting.."
-	exit 1
+    echo "not existing dir $REPO_DIR or $USER does not have writable permissions, exiting.."
+    exit 1
 fi
 
 PWD=`pwd`
@@ -76,7 +75,7 @@ cd $REPO_DIR
     #clean up
     OLDRPMS=`repomanage --keep=$KEEP_PKGS --old   $REPO_DIR 2>/dev/null`
     if [ ! -z "$OLDRPMS" ]; then
-          echo "$OLDRPMS" | xargs rm -rf
+        echo "$OLDRPMS" | xargs rm -rf
     fi
 
     if [ -z "$NO_SIGN" ]; then
@@ -84,12 +83,12 @@ cd $REPO_DIR
         if [ ! -z "$RESIGN_PACKAGES" ]; then
             #first key if not defined
             if [ -z "$GPGKEY" ]; then
-	            echo "getting first GPGKEY.."
-	            GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
+                echo "getting first GPGKEY.."
+                GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
             fi
             if [ -z "$GPGKEY" ]; then
-	            echo "GPGKEY not found, exiting..."
-	            exit 1
+                echo "GPGKEY not found, exiting..."
+                exit 1
             fi
             GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
             if [ ! -z "$GPG_NAME" ]; then
@@ -100,22 +99,22 @@ cd $REPO_DIR
                 GPG_LC=`echo $GPGKEY  | awk '{print tolower($0)}'`
 
                 find $REPO_DIR -type f -name "*.rpm"  | while read ENTRY
-                    do
+                do
                     RES=`rpm -K "$ENTRY"  -v | grep OK | grep $GPG_LC`
                     if [ $? -ne 0 ]; then
-                      #echo "signing $ENTRY by KEY:$GPGKEY  NAME:$GPG_NAME"
-                      rpm --addsign -D "_signature gpg" -D "_gpg_name $GPG_NAME"  "$ENTRY" $VERBOSE
+                        #echo "signing $ENTRY by KEY:$GPGKEY  NAME:$GPG_NAME"
+                        rpm --addsign -D "_signature gpg" -D "_gpg_name $GPG_NAME"  "$ENTRY" $VERBOSE
                     fi
                 done
             fi
         fi
-    fi 
+    fi
 
     #generate repo
     createrepo $UPDATE_REPO_FLAG $CLL_FLAG $REPO_DIR $VERBOSE
     if [ $? -ne 0 ]; then
-          echo "createrepo failed."
-          exit 1
+        echo "createrepo failed."
+        exit 1
     fi
 
     if [ -z "$NO_SIGN" ]; then
diff --git a/jss-xml-validator b/jss-xml-validator
--- a/jss-xml-validator
+++ b/jss-xml-validator
@@ -15,7 +15,7 @@ usage() {
     echo " options: "
     echo " -h,   --help ........................ shows command line help"
     echo " -ext, --extension <ext>  ............ choose extension (default xml)"
-    echo " -dtd <dtd-file>  .................... use DTD (Document Type Definition)"    
+    echo " -dtd <dtd-file>  .................... use DTD (Document Type Definition)"
     echo " -xsd <xsd-file>  .................... use XSD (W3C XML schema valiadtion)"
     echo " -V,   --version ..................... prints version of scripts"
     echo " Note: by default (without dtd/xsd files) performs only syntax check"
@@ -29,44 +29,44 @@ ERROR_COUNT=0
 ERROR_FILES_COUNT=0
 EXT=xml
 while [ $# -gt 0 ]; do
-  case "$1" in
-    --help) 
-        usage 
-        exit 
+    case "$1" in
+        --help)
+            usage
+            exit
         ;;
-    -ext | --extension )  
-        shift
-        EXT=$1
-        ;;         
-    -dtd ) 
-        shift
-        DTD_FLAGS="--dtdvalid $1"
+        -ext | --extension )
+            shift
+            EXT=$1
         ;;
-    -xsd )
-        shift 
-        XSD_FLAGS="--schema  $1"
+        -dtd )
+            shift
+            DTD_FLAGS="--dtdvalid $1"
         ;;
-    -V | --version) echo "$BASENAME ${VERSION} ${VERSION_DATE}"
-        exit 0
+        -xsd )
+            shift
+            XSD_FLAGS="--schema  $1"
         ;;
-    * )      
-        if [ -z "$SEARCH_DIR" ] && [ -e "$1" ] ; then
-            SEARCH_DIR=$1 ;
-        else
-            echo "Directory has to exist and there can be only one directory argument, exiting.."
-            exit 1
-        fi 
+        -V | --version) echo "$BASENAME ${VERSION} ${VERSION_DATE}"
+            exit 0
         ;;
-  esac
-  shift
+        * )
+            if [ -z "$SEARCH_DIR" ] && [ -e "$1" ] ; then
+                SEARCH_DIR=$1 ;
+            else
+                echo "Directory has to exist and there can be only one directory argument, exiting.."
+                exit 1
+            fi
+        ;;
+    esac
+    shift
 done
 EXT_RE=`printf '\.%s$' $EXT`
 
 if [ -z "$SEARCH_DIR" ] || [ ! -e "$SEARCH_DIR" ]; then
-	SEARCH_DIR="./"
+    SEARCH_DIR="./"
 fi
 
-#check if terminal supports colors 
+#check if terminal supports colors
 COLORS=
 if [ -x /usr/bin/tput ] && tput setaf > /dev/null; then
     COLORS=" --color=always ";
@@ -74,8 +74,8 @@ fi
 
 #check dependencies
 if ! type xmllint >/dev/null 2>&1; then
-  echo "Not installed xmllint, exiting.."
-  exit 1
+    echo "Not installed xmllint, exiting.."
+    exit 1
 fi
 
 FIND_WHOLENAME_FLAG="-wholename"
@@ -87,22 +87,22 @@ FILES_COUNT=`echo "$FILES" | grep -v '^$' | wc -l `
 
 echo "${FILES}" | \
 { while IFS='\n' read -r FILE ; do
-	ERRORS=`xmllint --noout $FILE $DTD_FLAGS $XSD_FLAGS  2>&1`
-    if [ $? != 0 ]; then
-        EC=`echo "$ERRORS" | grep -v '^$' | wc -l `
-        if [ -z "$COLORS" ]; then
-            echo "$FILE ($EC)";
-        else
-            echo "\033[01;34m$FILE\033[0m \033[01;31m($EC)\033[0m";
+        ERRORS=`xmllint --noout $FILE $DTD_FLAGS $XSD_FLAGS  2>&1`
+        if [ $? != 0 ]; then
+            EC=`echo "$ERRORS" | grep -v '^$' | wc -l `
+            if [ -z "$COLORS" ]; then
+                echo "$FILE ($EC)";
+            else
+                echo "\033[01;34m$FILE\033[0m \033[01;31m($EC)\033[0m";
+            fi
+            echo "$ERRORS"
+            ERROR_COUNT=$(($ERROR_COUNT + $EC)) ;
+            ERROR_FILES_COUNT=$(($ERROR_FILES_COUNT + 1)) ;
         fi
-        echo "$ERRORS"
-        ERROR_COUNT=$(($ERROR_COUNT + $EC)) ;
-        ERROR_FILES_COUNT=$(($ERROR_FILES_COUNT + 1)) ;
-    fi
-  done
-  
-  ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
-  echo "$BASENAME found \033[42m$ERROR_COUNT problems in $ERROR_FILES_COUNT files (checked $FILES_COUNT $EXT files) \033[0m, took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
-  exit $ERROR_COUNT
+    done
+    
+    ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
+    echo "$BASENAME found \033[42m$ERROR_COUNT problems in $ERROR_FILES_COUNT files (checked $FILES_COUNT $EXT files) \033[0m, took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
+    exit $ERROR_COUNT
 } || exit 2
 
