New: lock for debrepo updates, Int:formatting
Signed-off-by: Miroslav Safr <Miroslav.Safr@gmail.com>

diff --git a/jss-debrepo-update b/jss-debrepo-update
--- a/jss-debrepo-update
+++ b/jss-debrepo-update
@@ -45,39 +45,46 @@ if [ -z "$GPGKEY" ]; then
 fi
 GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
 
-#clean up
-rm -f $REPO_DIR/Packages $REPO_DIR/Packages.gz $REPO_DIR/Sources $REPO_DIR/Sources.gz $REPO_DIR/Release $REPO_DIR/InRelease $REPO_DIR/Release.gpg 
+#when the repo is updated too often lock is needed
+(
+  exec 8> $REPO_DIR/.lock;
+  flock --timeout 120 -e 8
+  echo " $$ locking repo $REPO_DIR at `date +'%T'`"
+
+  #clean up
+  rm -f $REPO_DIR/Packages $REPO_DIR/Packages.gz $REPO_DIR/Sources $REPO_DIR/Sources.gz $REPO_DIR/Release $REPO_DIR/InRelease $REPO_DIR/Release.gpg 
 
 
-#check signs and resign
-jss-debrepo-signcheck $REPO_DIR
-if [ $? -ne 0 ]; then
-	echo "not sign packages in repo - resigning"
-	PACKAGES=`find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes|dsc)$'`
-	echo "${PACKAGES}" | \
-	{ while IFS='\n' read -r ENTRY ;
-	do
-		echo "test:$ENTRY"
-		RES=`dpkg-sig -c $ENTRY | grep $GPGKEY`
-		if [ $? -ne 0 ]; then
-			"signing> $SIGN_NAME KEY:$GPGKEY FILE:$ENTRY"
-			dpkg-sig -s $SIGN_NAME -k $GPGKEY $ENTRY
-	  	fi
-	done
-	}
-else 
-	echo "jss-debrepo-signcheck=0"
-fi
+  #check signs and resign
+  jss-debrepo-signcheck $REPO_DIR
+  if [ $? -ne 0 ]; then
+	  echo "not sign packages in repo - resigning"
+	  PACKAGES=`find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes|dsc)$'`
+	  echo "${PACKAGES}" | \
+	  { while IFS='\n' read -r ENTRY ;
+	  do
+		  echo "test:$ENTRY"
+		  RES=`dpkg-sig -c $ENTRY | grep $GPGKEY`
+		  if [ $? -ne 0 ]; then
+			  "signing> $SIGN_NAME KEY:$GPGKEY FILE:$ENTRY"
+			  dpkg-sig -s $SIGN_NAME -k $GPGKEY $ENTRY
+	    	fi
+	  done
+	  }
+  else 
+	  echo "jss-debrepo-signcheck=0"
+  fi
 
-#recreate
-dpkg-scanpackages  $REPO_DIR/ /dev/null  >   $REPO_DIR/Packages
-cat $REPO_DIR/Packages | gzip -9 >  $REPO_DIR/Packages.gz 
-dpkg-scansources  $REPO_DIR/  >  $REPO_DIR/Sources
-cat $REPO_DIR/Sources | gzip -9 >  $REPO_DIR/Sources.gz 
+  #recreate
+  dpkg-scanpackages  $REPO_DIR/ /dev/null  >   $REPO_DIR/Packages
+  cat $REPO_DIR/Packages | gzip -9 >  $REPO_DIR/Packages.gz 
+  dpkg-scansources  $REPO_DIR/  >  $REPO_DIR/Sources
+  cat $REPO_DIR/Sources | gzip -9 >  $REPO_DIR/Sources.gz 
 
-#release sign
-apt-ftparchive release $REPO_DIR > $REPO_DIR/Release
-gpg --clearsign -o $REPO_DIR/InRelease $REPO_DIR/Release
-gpg -abs -o $REPO_DIR/Release.gpg $REPO_DIR/Release
+  #release sign
+  apt-ftparchive release $REPO_DIR > $REPO_DIR/Release
+  gpg --clearsign -o $REPO_DIR/InRelease $REPO_DIR/Release
+  gpg -abs -o $REPO_DIR/Release.gpg $REPO_DIR/Release
 
+) || exit 1
 
diff --git a/jss-rpmrepo-update b/jss-rpmrepo-update
--- a/jss-rpmrepo-update
+++ b/jss-rpmrepo-update
@@ -73,50 +73,50 @@ fi
   flock --timeout 120 -e 8
   echo " $$ locking repo $REPO_DIR at `date +'%T'`"
 
-#clean up
-OLDRPMS=`repomanage --keep=$KEEP_PKGS --old   $REPO_DIR 2>/dev/null`
-if [ ! -z "$OLDRPMS" ]; then
-		echo "$OLDRPMS" | xargs rm -rf
-fi
+  #clean up
+  OLDRPMS=`repomanage --keep=$KEEP_PKGS --old   $REPO_DIR 2>/dev/null`
+  if [ ! -z "$OLDRPMS" ]; then
+	      echo "$OLDRPMS" | xargs rm -rf
+  fi
 
 
-#optional resigning
-if [ ! -z "$RESIGN_PACKAGES" ]; then
-	GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
-	if [ ! -z "$GPG_NAME" ]; then
-		if [ -z "$GPGKEY" ]; then
-			GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
-			echo "using first GPGKEY: $GPGKEY"
-		fi
-		GPG_LC=`echo $GPGKEY  | awk '{print tolower($0)}'`
-
-		find $REPO_DIR -type f -name "*.rpm"  | while read ENTRY
-		do
-		  RES=`rpm -K "$ENTRY"  -v | grep OK | grep $GPG_LC`
-		  if [ $? -ne 0 ]; then
-		        #echo "signing $ENTRY by KEY:$GPGKEY  NAME:$GPG_NAME"
-		        rpm --addsign -D "_signature gpg" -D "_gpg_name $GPG_NAME"  "$ENTRY" $VERBOSE
+  #optional resigning
+  if [ ! -z "$RESIGN_PACKAGES" ]; then
+	  GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
+	  if [ ! -z "$GPG_NAME" ]; then
+		  if [ -z "$GPGKEY" ]; then
+			  GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
+			  echo "using first GPGKEY: $GPGKEY"
 		  fi
-		done
-	fi
-fi
+		  GPG_LC=`echo $GPGKEY  | awk '{print tolower($0)}'`
 
-#generate repo
-createrepo $UPDATE_REPO_FLAG $CLL_FLAG $REPO_DIR $VERBOSE
-if [ $? -ne 0 ]; then
-	echo "createrepo failed."
-	exit 1
-fi
+		  find $REPO_DIR -type f -name "*.rpm"  | while read ENTRY
+		  do
+		    RES=`rpm -K "$ENTRY"  -v | grep OK | grep $GPG_LC`
+		    if [ $? -ne 0 ]; then
+		          #echo "signing $ENTRY by KEY:$GPGKEY  NAME:$GPG_NAME"
+		          rpm --addsign -D "_signature gpg" -D "_gpg_name $GPG_NAME"  "$ENTRY" $VERBOSE
+		    fi
+		  done
+	  fi
+  fi
 
-#sign repo
-if [ -z "$GPGKEY" ]; then
-  GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
-  echo "reposign uses first GPGKEY: $GPGKEY"
-fi
-gpg -u $GPGKEY --detach-sign --yes --armor  $REPO_DIR/repodata/repomd.xml
-if [ $? -ne 0 ]; then
-  echo "repo resign failed."
-fi
+  #generate repo
+  createrepo $UPDATE_REPO_FLAG $CLL_FLAG $REPO_DIR $VERBOSE
+  if [ $? -ne 0 ]; then
+	  echo "createrepo failed."
+	  exit 1
+  fi
+
+  #sign repo
+  if [ -z "$GPGKEY" ]; then
+    GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
+    echo "reposign uses first GPGKEY: $GPGKEY"
+  fi
+  gpg -u $GPGKEY --detach-sign --yes --armor  $REPO_DIR/repodata/repomd.xml
+  if [ $? -ne 0 ]; then
+    echo "repo resign failed."
+  fi
 
 ) || exit 1
 
