New: jss-debrepo-signcheck, Fix: jss-rpmrepo-update exit code update
Signed-off-by: Miroslav Safr <Miroslav.Safr@gmail.com>

diff --git a/jss-rpmrepo-update b/jss-rpmrepo-update
--- a/jss-rpmrepo-update
+++ b/jss-rpmrepo-update
@@ -47,3 +47,8 @@ fi
 
 #generate repo
 createrepo  $REPO_DIR
+if [ $? -ne 0 ]; then
+	echo "createrepo failed."
+	exit 1
+fi
+
